# Generated by Django 4.1.2 on 2022-10-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='body',
            new_name='description',
        ),
    ]
