# Generated by Django 4.1.2 on 2022-10-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_body_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
