# Generated by Django 4.1.2 on 2022-10-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_item_meta_description_remove_item_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='publish_date',
        ),
    ]
