# Generated by Django 3.2.16 on 2022-11-11 11:44

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.get_image_path),
        ),
    ]
